import type { TemplateItem } from "@/types/prompt";

export const categoryMeta: Record<string, { label: string; desc: string; structure: string[] }> = {
  coding: { label: "Coding", desc: "Debug review generate code", structure: ["Role","Language","Context","Requirements","Constraints","Output","Error Handling"] },
  writing: { label: "Writing", desc: "Artikel email story", structure: ["Role","Topic","Audience","Tone","Structure","Length","Output Format"] },
  research: { label: "Research", desc: "Kajian dan ringkasan", structure: ["Objective","Context","Scope","Sources","Methodology","Output","Limitations"] },
  marketing: { label: "Marketing", desc: "Campaign dan copy", structure: ["Role","Product","Audience","Goal","Channel","Tone","CTA"] },
  education: { label: "Education", desc: "Materi dan kurikulum", structure: ["Role","Topic","Level","Objective","Format","Examples","Assessment"] },
  image: { label: "Image Generation", desc: "Prompt visual", structure: ["Subject","Style","Composition","Lighting","Camera","Environment","Mood"] },
  data: { label: "Data Analysis", desc: "Analisis dan visualisasi", structure: ["Role","Dataset","Goal","Method","Output","Constraints"] },
  business: { label: "Business", desc: "Strategi dan plan", structure: ["Role","Context","Objective","Constraints","Output","Metrics"] },
  general: { label: "General", desc: "Serbaguna", structure: ["Role","Objective","Context","Requirements","Output Format"] },
};

export const templates: TemplateItem[] = [
  // CODING 6
  { id:"code-review", title:"Code Review", category:"coding", description:"Minta review kode yang ketat dan actionable", prompt:"Review kode {LANGUAGE} berikut untuk {FOCUS}. Beri skor bug dan saran refactor:\n\n```{LANGUAGE}\n{CODE}\n```", vars:[{key:"LANGUAGE",label:"Bahasa",placeholder:"TypeScript"}, {key:"FOCUS",label:"Fokus",placeholder:"performance"}, {key:"CODE",label:"Kode",placeholder:"paste kode..."}] },
  { id:"debug", title:"Debug Assistant", category:"coding", description:"Cari akar masalah dan solusi", prompt:"Kamu senior {LANGUAGE} engineer. Debug error berikut:\nError: {ERROR}\nContext: {CONTEXT}\nBeri penyebab solusi dan pencegahan.", vars:[{key:"LANGUAGE",label:"Bahasa",placeholder:"Next.js"}, {key:"ERROR",label:"Pesan error",placeholder:"Hydration failed..."}, {key:"CONTEXT",label:"Konteks",placeholder:"saat build..."}] },
  { id:"gen-api", title:"Generate API", category:"coding", description:"Buat endpoint REST lengkap", prompt:"Buatkan API {METHOD} {ENDPOINT} dengan {FRAMEWORK}. Validasi {VALIDATION} dan response {RESPONSE}. Sertakan error handling dan test.", vars:[{key:"METHOD",label:"Method",placeholder:"POST"}, {key:"ENDPOINT",label:"Endpoint",placeholder:"/api/history"}, {key:"FRAMEWORK",label:"Framework",placeholder:"Next.js"}, {key:"VALIDATION",label:"Validasi",placeholder:"zod"}, {key:"RESPONSE",label:"Response",placeholder:"JSON"}] },
  { id:"refactor", title:"Refactor Code", category:"coding", description:"Rapikan kode jadi clean", prompt:"Refactor kode {LANGUAGE} ini agar lebih clean dan performant untuk {GOAL}. Jelaskan perubahan dan trade off:\n\n{CODE}", vars:[{key:"LANGUAGE",label:"Bahasa",placeholder:"React"}, {key:"GOAL",label:"Goal",placeholder:"readability"}, {key:"CODE",label:"Kode",placeholder:"paste kode..."}] },
  { id:"explain-code", title:"Explain Code", category:"coding", description:"Jelaskan kode baris per baris", prompt:"Jelaskan kode {LANGUAGE} berikut untuk level {LEVEL}. Uraikan alur logika dan potensi bug:\n\n{CODE}", vars:[{key:"LANGUAGE",label:"Bahasa",placeholder:"Python"}, {key:"LEVEL",label:"Level",placeholder:"pemula"}, {key:"CODE",label:"Kode",placeholder:"paste kode..."}] },
  { id:"write-tests", title:"Write Tests", category:"coding", description:"Buat unit test", prompt:"Buatkan unit test {FRAMEWORK} untuk fungsi {FUNCTION} dengan coverage {COVERAGE}. Sertakan edge case:\n\n{CODE}", vars:[{key:"FRAMEWORK",label:"Framework",placeholder:"Vitest"}, {key:"FUNCTION",label:"Fungsi",placeholder:"optimizePrompt"}, {key:"COVERAGE",label:"Coverage",placeholder:"80%"}, {key:"CODE",label:"Kode",placeholder:"paste kode..."}] },

  // WRITING 6
  { id:"blog", title:"Blog Article", category:"writing", description:"Artikel SEO terstruktur", prompt:"Tulis artikel {LENGTH} tentang {TOPIC} untuk audiens {AUDIENCE} dengan tone {TONE}. Struktur hook 3 poin utama kesimpulan plus CTA.", vars:[{key:"TOPIC",label:"Topik",placeholder:"Prompt Engineering"}, {key:"AUDIENCE",label:"Audiens",placeholder:"mahasiswa"}, {key:"TONE",label:"Tone",placeholder:"edukatif"}, {key:"LENGTH",label:"Panjang",placeholder:"800 kata"}] },
  { id:"linkedin-post", title:"LinkedIn Post", category:"writing", description:"Post profesional yang hook", prompt:"Buat LinkedIn post tentang {TOPIC} untuk {AUDIENCE}. Goal {GOAL}. Gaya {TONE}. Mulai dengan hook kuat dan akhiri dengan pertanyaan.", vars:[{key:"TOPIC",label:"Topik",placeholder:"AI untuk mahasiswa"}, {key:"AUDIENCE",label:"Audiens",placeholder:"recruiter"}, {key:"GOAL",label:"Goal",placeholder:"engagement"}, {key:"TONE",label:"Tone",placeholder:"inspiratif"}] },
  { id:"email", title:"Email Profesional", category:"writing", description:"Email formal siap kirim", prompt:"Tulis email {TONE} untuk {RECIPIENT} tentang {TOPIC}. Tujuan {GOAL}. Panjang {LENGTH}.", vars:[{key:"RECIPIENT",label:"Penerima",placeholder:"dosen"}, {key:"TOPIC",label:"Topik",placeholder:"izin penelitian"}, {key:"GOAL",label:"Tujuan",placeholder:"mendapat persetujuan"}, {key:"TONE",label:"Tone",placeholder:"formal"}, {key:"LENGTH",label:"Panjang",placeholder:"150 kata"}] },
  { id:"product-desc", title:"Product Description", category:"writing", description:"Deskripsi produk yang menjual", prompt:"Buat deskripsi produk {PRODUCT} untuk {AUDIENCE}. Highlight {FEATURE} dan manfaat {BENEFIT}. Tone {TONE}.", vars:[{key:"PRODUCT",label:"Produk",placeholder:"PromptForge"}, {key:"AUDIENCE",label:"Audiens",placeholder:"mahasiswa"}, {key:"FEATURE",label:"Fitur",placeholder:"optimizer prompt"}, {key:"BENEFIT",label:"Manfaat",placeholder:"hemat waktu"}, {key:"TONE",label:"Tone",placeholder:"persuasif"}] },
  { id:"story", title:"Story", category:"writing", description:"Cerita pendek", prompt:"Tulis cerita pendek tentang {TOPIC} dengan tokoh {CHARACTER} setting {SETTING} dan konflik {CONFLICT}. Gaya {TONE}.", vars:[{key:"TOPIC",label:"Topik",placeholder:"bengkel tempa prompt"}, {key:"CHARACTER",label:"Tokoh",placeholder:"mahasiswa"}, {key:"SETTING",label:"Setting",placeholder:"kampus"}, {key:"CONFLICT",label:"Konflik",placeholder:"deadline"}, {key:"TONE",label:"Tone",placeholder:"hangat"}] },
  { id:"essay", title:"Essay Akademik", category:"writing", description:"Essay terstruktur", prompt:"Tulis essay {LENGTH} tentang {TOPIC} dengan argumen {ARGUMEN} dan referensi {REF}. Struktur pembuka isi penutup.", vars:[{key:"TOPIC",label:"Topik",placeholder:"etika AI"}, {key:"ARGUMEN",label:"Argumen",placeholder:"AI membantu belajar"}, {key:"REF",label:"Referensi",placeholder:"3 jurnal"}, {key:"LENGTH",label:"Panjang",placeholder:"600 kata"}] },

  // RESEARCH 4
  { id:"research-plan", title:"Research Plan", category:"research", description:"Rencana riset komprehensif", prompt:"Buat research plan untuk topik {TOPIC} scope {SCOPE}. Sertakan objective metodologi sumber primer output format tabel dan limitations.", vars:[{key:"TOPIC",label:"Topik",placeholder:"AI in education"}, {key:"SCOPE",label:"Scope",placeholder:"Indonesia 2024 2026"}] },
  { id:"lit-review", title:"Literature Review", category:"research", description:"Rangkuman literatur", prompt:"Buat literature review untuk {TOPIC}. Bandingkan {COUNT} sumber utama dan rangkum gap riset dalam tabel.", vars:[{key:"TOPIC",label:"Topik",placeholder:"prompt engineering"}, {key:"COUNT",label:"Jumlah",placeholder:"5"}] },
  { id:"compare-topics", title:"Bandingkan Topik", category:"research", description:"Komparasi dua topik", prompt:"Bandingkan {TOPIC_A} dan {TOPIC_B} dari sisi {ASPEK}. Hasilkan tabel perbandingan dan rekomendasi.", vars:[{key:"TOPIC_A",label:"Topik A",placeholder:"Supabase"}, {key:"TOPIC_B",label:"Topik B",placeholder:"Firebase"}, {key:"ASPEK",label:"Aspek",placeholder:"harga dan skalabilitas"}] },
  { id:"research-summary", title:"Research Summary", category:"research", description:"Ringkasan cepat", prompt:"Ringkas dokumen {DOC} untuk audiens {AUDIENCE} sepanjang {LENGTH}. Ambil 5 poin utama dan simpulan.", vars:[{key:"DOC",label:"Dokumen",placeholder:"paper AI"}, {key:"AUDIENCE",label:"Audiens",placeholder:"mahasiswa"}, {key:"LENGTH",label:"Panjang",placeholder:"200 kata"}] },

  // MARKETING 4
  { id:"campaign", title:"Marketing Campaign", category:"marketing", description:"Campaign 7 hari", prompt:"Buat campaign {CHANNEL} untuk produk {PRODUCT} targeting {AUDIENCE}. Goal {GOAL}. Beri hook content pillar 3 copy dan CTA.", vars:[{key:"PRODUCT",label:"Produk",placeholder:"PromptForge"}, {key:"AUDIENCE",label:"Audiens",placeholder:"mahasiswa"}, {key:"CHANNEL",label:"Channel",placeholder:"Instagram"}, {key:"GOAL",label:"Goal",placeholder:"signups"}] },
  { id:"ads-copy", title:"Ads Copy", category:"marketing", description:"Copy iklan 3 varian", prompt:"Buat 3 varian ads copy untuk {PRODUCT} audiens {AUDIENCE} channel {CHANNEL} dengan angle {ANGLE}.", vars:[{key:"PRODUCT",label:"Produk",placeholder:"PromptForge Pro"}, {key:"AUDIENCE",label:"Audiens",placeholder:"developer"}, {key:"CHANNEL",label:"Channel",placeholder:"Meta Ads"}, {key:"ANGLE",label:"Angle",placeholder:"hemat waktu"}] },
  { id:"seo-brief", title:"SEO Brief", category:"marketing", description:"Brief konten SEO", prompt:"Buat SEO brief untuk keyword {KEYWORD} target {AUDIENCE}. Sertakan outline FAQ dan internal linking.", vars:[{key:"KEYWORD",label:"Keyword",placeholder:"prompt engineering"}, {key:"AUDIENCE",label:"Audiens",placeholder:"pemula"}] },
  { id:"landing-copy", title:"Landing Copy", category:"marketing", description:"Copy landing page", prompt:"Tulis hero headline subheadline dan 3 benefit untuk produk {PRODUCT} audiens {AUDIENCE} dengan tone {TONE}.", vars:[{key:"PRODUCT",label:"Produk",placeholder:"PromptForge"}, {key:"AUDIENCE",label:"Audiens",placeholder:"mahasiswa"}, {key:"TONE",label:"Tone",placeholder:"ramah"}] },

  // EDUCATION 3
  { id:"lesson", title:"Lesson Plan", category:"education", description:"RPP 1 pertemuan", prompt:"Buat lesson plan untuk {TOPIC} level {LEVEL}. Objective {OBJECTIVE} durasi 90 menit. Sertakan aktivitas contoh dan asesmen.", vars:[{key:"TOPIC",label:"Topik",placeholder:"Prompt Engineering"}, {key:"LEVEL",label:"Level",placeholder:"SMA"}, {key:"OBJECTIVE",label:"Objective",placeholder:"memahami role dan context"}] },
  { id:"quiz", title:"Quiz Builder", category:"education", description:"Buat quiz 10 soal", prompt:"Buat quiz 10 soal {TYPE} untuk topik {TOPIC} level {LEVEL}. Sertakan jawaban dan pembahasan.", vars:[{key:"TYPE",label:"Tipe",placeholder:"pilihan ganda"}, {key:"TOPIC",label:"Topik",placeholder:"AI dasar"}, {key:"LEVEL",label:"Level",placeholder:"SMA"}] },
  { id:"summary-edu", title:"Ringkasan Materi", category:"education", description:"Ringkasan cepat", prompt:"Ringkas materi {TOPIC} untuk {LEVEL} sepanjang {LENGTH}. Gunakan poin dan contoh konkret.", vars:[{key:"TOPIC",label:"Topik",placeholder:"machine learning"}, {key:"LEVEL",label:"Level",placeholder:"mahasiswa baru"}, {key:"LENGTH",label:"Panjang",placeholder:"300 kata"}] },

  // IMAGE 2
  { id:"image-gen", title:"Image Prompt Pro", category:"image", description:"Prompt Midjourney SD siap pakai", prompt:"Subject: {SUBJECT}, Style: {STYLE}, Lighting: {LIGHTING}, Camera: {CAMERA}, Environment: {ENV}, Mood: {MOOD} ar 16 per 9 style raw", vars:[{key:"SUBJECT",label:"Subject",placeholder:"mahasiswa di bengkel tempa"}, {key:"STYLE",label:"Style",placeholder:"cinematic"}, {key:"LIGHTING",label:"Lighting",placeholder:"warm ember glow"}, {key:"CAMERA",label:"Camera",placeholder:"35mm"}, {key:"ENV",label:"Environment",placeholder:"workshop"}, {key:"MOOD",label:"Mood",placeholder:"focused"}] },
  { id:"logo-prompt", title:"Logo Prompt", category:"image", description:"Prompt logo minimalis", prompt:"Buat prompt logo untuk brand {BRAND} gaya {STYLE} warna {COLOR} dengan vibe {VIBE} untuk background {BG}.", vars:[{key:"BRAND",label:"Brand",placeholder:"PromptForge"}, {key:"STYLE",label:"Style",placeholder:"minimalist"}, {key:"COLOR",label:"Warna",placeholder:"ink dan ember"}, {key:"VIBE",label:"Vibe",placeholder:"modern"}, {key:"BG",label:"Background",placeholder:"putih"}] },

  // DATA 3
  { id:"data-analysis", title:"Data Analysis Brief", category:"data", description:"Brief analisis dataset", prompt:"Analisis dataset {DATASET} untuk menjawab {QUESTION}. Metode {METHOD} output {OUTPUT}. Sertakan caveats dan visualisasi yang disarankan.", vars:[{key:"DATASET",label:"Dataset",placeholder:"penjualan PromptForge"}, {key:"QUESTION",label:"Pertanyaan",placeholder:"kategori paling populer"}, {key:"METHOD",label:"Metode",placeholder:"cohort"}, {key:"OUTPUT",label:"Output",placeholder:"dashboard"}] },
  { id:"sql-query", title:"SQL Query", category:"data", description:"Buat query SQL", prompt:"Buatkan query {DIALECT} untuk {GOAL} dari tabel {TABLE} dengan filter {FILTER}. Jelaskan tiap klausa.", vars:[{key:"DIALECT",label:"Dialek",placeholder:"Postgres"}, {key:"GOAL",label:"Goal",placeholder:"hitung MAU"}, {key:"TABLE",label:"Tabel",placeholder:"prompts"}, {key:"FILTER",label:"Filter",placeholder:"created_at > 7 hari"}] },
  { id:"viz-brief", title:"Visualisasi", category:"data", description:"Brief chart", prompt:"Rekomendasikan visualisasi untuk data {DATA} tujuan {GOAL} audiens {AUDIENCE}. Beri alasan pemilihan chart.", vars:[{key:"DATA",label:"Data",placeholder:"history penggunaan"}, {key:"GOAL",label:"Goal",placeholder:"tren harian"}, {key:"AUDIENCE",label:"Audiens",placeholder:"manajemen"}] },

  // BUSINESS 3
  { id:"business-plan", title:"Business One Pager", category:"business", description:"Ringkasan bisnis 1 halaman", prompt:"Buat business one pager untuk {IDEA} targeting {AUDIENCE}. Sertakan problem solusi model metrics dan next step.", vars:[{key:"IDEA",label:"Ide",placeholder:"PromptForge"}, {key:"AUDIENCE",label:"Audiens",placeholder:"investor awal"}] },
  { id:"pitch-deck", title:"Pitch Outline", category:"business", description:"Outline pitch deck", prompt:"Buat outline pitch deck 10 slide untuk {IDEA} audiens {AUDIENCE} dengan highlight {HIGHLIGHT}.", vars:[{key:"IDEA",label:"Ide",placeholder:"PromptForge"}, {key:"AUDIENCE",label:"Audiens",placeholder:"investor"}, {key:"HIGHLIGHT",label:"Highlight",placeholder:"traction"}] },
  { id:"swot", title:"SWOT Analysis", category:"business", description:"Analisis SWOT", prompt:"Buat SWOT untuk {BISNIS} konteks {KONTEKS}. Beri 4 poin tiap kuadran dan rekomendasi.", vars:[{key:"BISNIS",label:"Bisnis",placeholder:"PromptForge"}, {key:"KONTEKS",label:"Konteks",placeholder:"kampus"}] },

  // GENERAL 2
  { id:"general-pro", title:"General Pro", category:"general", description:"Prompt serbaguna rapi", prompt:"Rapikan prompt berikut jadi struktur Role Objective Context Requirements dan Output Format:\n\n{TEXT}", vars:[{key:"TEXT",label:"Teks",placeholder:"paste prompt mentah..."}] },
  { id:"susun-ulang", title:"Susun Ulang", category:"general", description:"Perjelas instruksi vage", prompt:"Ubah instruksi vage ini jadi prompt yang jelas dan siap pakai untuk {MODEL}:\n\n{TEXT}", vars:[{key:"MODEL",label:"Model",placeholder:"ChatGPT"}, {key:"TEXT",label:"Teks",placeholder:"bikin caption..."}] },
];
